# https://www.home-assistant.io/integrations/sensor.command_line
# - platform: command_line
#   name: CPU Temperature
#   command: 'cat /sys/class/thermal/thermal_zone0/temp'
#   unit_of_measurement: '°C'
# #   device_class: 'temperature'
#   value_template: '{{ value | multiply(0.001) | round(1) }}'

# - platform: command_line
#   name: GPU Temperature
#   command: '/opt/vc/bin/vcgencmd measure_temp'
#   unit_of_measurement: '°C'
# #   device_class: 'temperature'
#   value_template: '{{ value | replace("temp=", "") | replace("''C", "") }}'

# https://www.home-assistant.io/integrations/file#sensor
# - platform: file
#   name: Electricity Usage - Last Bill
#   file_path: !secret electricity_usage
#   value_template: '{{ value_json.usage }}'
#   unit_of_measurement: kWh

# - platform: file
#   name: Water Usage CCF - Last Bill
#   file_path: !secret water_usage
#   value_template: '{{ value_json.usage }}'
#   unit_of_measurement: CCF

# - platform: file
#   name: Water Usage - Last Bill
#   file_path: !secret water_usage
#   value_template: '{{ (value_json.usage * 748.05194805) | round(0) }}'
#   unit_of_measurement: gal

# - platform: file
#   name: Gas Usage - Last Bill
#   file_path: !secret gas_usage
#   value_template: '{{ value_json.usage }}'
#   unit_of_measurement: gal


# https://www.home-assistant.io/integrations/google_wifi
- platform: google_wifi
  name: Google Wifi
  host: 192.168.86.1
  monitored_conditions:
    - uptime
    - status

# https://www.home-assistant.io/integrations/imap_email_content/
- platform: imap_email_content
  name: ting
  server: imap.gmail.com
  port: 993
  username: !secret gmail_username
  password: !secret gmail_app_password
  folder: INBOX
  senders:
    - help@whiskerlabs.com

# https://www.home-assistant.io/integrations/sensor.mqtt/
# - platform: mqtt
#   name: Water Consumption
#   icon: mdi:water
#   unit_of_measurement: gal
#   state_topic: homeassistant/sensor/1461742372/reading
#   state_class: total_increasing
#   value_template: "{{ value_json.Message.Consumption }}"
#   json_attributes_topic: homeassistant/sensor/1461742372/reading
#   json_attributes_template: "{{ value_json | tojson }}"

# - platform: mqtt
#   name: Electricity Consumption
#   icon: mdi:flash
#   device_class: energy
#   unit_of_measurement: kWh
#   state_topic: homeassistant/sensor/69109638/reading
#   state_class: total_increasing
#   value_template: "{{ value_json.Message.Consumption | multiply(0.01) | round() }}"
#   json_attributes_topic: homeassistant/sensor/69109638/reading
#   json_attributes_template: "{{ value_json | tojson }}"

# https://www.home-assistant.io/integrations/systemmonitor
- platform: systemmonitor
  resources:
    # - type: disk_use_percent
    #   arg: /
    # - type: disk_use
    #   arg: /
    # - type: memory_use_percent
    # - type: memory_use
    # - type: network_in
    #   arg: eth0
    # - type: network_out
    #   arg: eth0
    # - type: processor_use
    - type: last_boot

# https://www.home-assistant.io/integrations/time_date/
- platform: time_date
  display_options:
    - 'time'
    - 'date'

# https://www.home-assistant.io/integrations/waqi/
- platform: waqi
  token: !secret aqi_api_token
  locations:
    - Londonderry - Moose Hill, New Hampshire
