# https://www.home-assistant.io/docs/configuration/secrets

# data usage
data_usage_url: http://debian.local:7878//homeassistant

# amerigas
amerigas_username: abcdefghijklmnopqrstuvwxyz0123456789
amerigas_password: abcdefghijklmnopqrstuvwxyz0123456789
