# files
database_file: home-assistant_v2.db

# utilities
gas_usage: .data/gas.ndjson
water_usage: .data/water.ndjson
electricity_usage: .data/electricity.ndjson

# data usage
data_usage_url: http://127.0.0.1:7878/homeassistant

# camera
camera_username: abcdefghijklmnopqrstuvwxyz0123456789
camera_password: abcdefghijklmnopqrstuvwxyz0123456789

camera_server_url: 127.0.0.1
camera_status_url: http://127.0.0.1:8083/status.json

driveway_camera_image_url: http://127.0.0.1:8083/axis-cgi/jpg/image.cgi?cameraId=0123456789
driveway_camera_video_url: http://127.0.0.1:8083/axis-cgi/mjpg/video.cgi?cameraId=0123456789
driveway_camera_image_url_auth: http://username:password@127.0.0.1:8083/axis-cgi/jpg/image.cgi?cameraId=0123456789

backyard_camera_image_url: http://127.0.0.1:8083/axis-cgi/jpg/image.cgi?cameraId=0123456789
backyard_camera_video_url: http://127.0.0.1:8083/axis-cgi/mjpg/video.cgi?cameraId=0123456789
backyard_camera_image_url_auth: http://username:password@127.0.0.1:8083/axis-cgi/jpg/image.cgi?cameraId=0123456789

kitchen_camera_image_url: http://127.0.0.1:8083/axis-cgi/jpg/image.cgi?cameraId=0123456789
kitchen_camera_video_url: http://127.0.0.1:8083/axis-cgi/mjpg/video.cgi?cameraId=0123456789

# ble sensor
bedroom_sensor_mac: A1:B2:C3:D4:E6:F7
basement_sensor_mac: A1:B2:C3:D4:E6:F7

# influxdb
influxdb_host: us-east-1-1.aws.cloud2.influxdata.com
influxdb_organization: abcdefghijklmnopqrstuvwxyz0123456789
influxdb_token: abcdefghijklmnopqrstuvwxyz0123456789

# aqicn.org
aqi_api_token: abcdefghijklmnopqrstuvwxyz0123456789
