# https://www.home-assistant.io/docs/configuration/secrets

# utilities
gas_usage: .data/gas.ndjson
water_usage: .data/water.ndjson
electricity_usage: .data/electricity.ndjson

# data usage
data_usage_url: http://debian.local:7878//homeassistant

# camera
camera_server_url: http://127.0.0.1

# amerigas
amerigas_username: abcdefghijklmnopqrstuvwxyz0123456789
amerigas_password: abcdefghijklmnopqrstuvwxyz0123456789

# imap
gmail_username: abcdefghijklmnopqrstuvwxyz0123456789
gmail_app_password: abcdefghijklmnopqrstuvwxyz0123456789

# influxdb
influxdb_host: us-east-1-1.aws.cloud2.influxdata.com
influxdb_organization: abcdefghijklmnopqrstuvwxyz0123456789
influxdb_token: abcdefghijklmnopqrstuvwxyz0123456789

# aqicn.org
aqi_api_token: abcdefghijklmnopqrstuvwxyz0123456789

# dark sky
dark_sky_api_key: abcdefghijklmnopqrstuvwxyz0123456789
