- id: '1605886570099'
  alias: Turn on living room lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 01:30
  condition: []
  action:
  - type: turn_on
    device_id: 0885ed2690b46239fb5097c82e1f1073
    entity_id: light.living_room
    domain: light
  mode: single
- id: '1605887171461'
  alias: Turn on staircase lights
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - type: turn_on
    device_id: ae7c7d7804c811eb8fa71deb0d3d0c10
    entity_id: switch.staircase_light
    domain: switch
  mode: single
- id: '1605887484325'
  alias: Turn on bedroom light
  description: ''
  trigger:
  - platform: time
    at: input_datetime.bedroom_light_on
  condition: []
  action:
  - type: turn_off
    device_id: 138506d6ceac3071a7ea57ba1d9b20c2
    entity_id: light.bedroom
    domain: light
  mode: single
- id: '1607973886251'
  alias: Turn off bedroom light
  description: ''
  trigger:
  - platform: time
    at: input_datetime.bedroom_light_off
  condition: []
  action:
  - type: turn_off
    device_id: 138506d6ceac3071a7ea57ba1d9b20c2
    entity_id: light.bedroom
    domain: light
  mode: single
- id: '1607978571172'
  alias: High water usage alert
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.hourly_water_consumption
    above: '20'
  condition: []
  action:
  - service: notify.mobile_app_abi_iphone_12
    data:
      message: High water usage
  mode: single
- id: '1608045125690'
  alias: Turn off living room lights
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 0885ed2690b46239fb5097c82e1f1073
    entity_id: light.living_room
    domain: light
  mode: single
- id: '1631369919205'
  alias: Check all doors
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  condition: []
  action:
  - service: notify.mobile_app_abi_iphone_12
    data:
      message: '{% set doors = expand(''group.doors'') | selectattr(''state'', ''in'',
        [''on'', ''open'']) | map(attribute=''name'') |  map(''replace'', '' Door'',
        '''')  | list %} {% set count = doors | count %} {% if count == 0 %} All doors
        are closed. {% else %} The {{ doors | join('', and '')}} door{{ ''s are ''
        if count > 1 else '' is '' }}open. {% endif %}'
      data:
        actions:
        - action: close_garage_door
          title: Close Garage Door
  mode: single
- id: '1631372133150'
  alias: Close Garage from iOS notification
  description: ''
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: close_garage_door
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.garage_door
  mode: single
- id: '1634055219482'
  alias: Turn off staircase lights
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: ae7c7d7804c811eb8fa71deb0d3d0c10
    entity_id: switch.staircase_light
    domain: switch
  mode: single
- id: '1640659914390'
  alias: Turn on grow light
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - type: turn_on
    device_id: 08c93d76a82320a1d00dc1690c839552
    entity_id: switch.grow_light
    domain: switch
  mode: single
- id: '1640659987844'
  alias: Turn off grow light
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 08c93d76a82320a1d00dc1690c839552
    entity_id: switch.grow_light
    domain: switch
  mode: single
- id: '1641389624938'
  alias: Set temperature for night
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 60
    target:
      device_id: 0e3b41f4d6adfcecbd7b25e030582a2a
  mode: single
- id: '1641389647705'
  alias: Set temperature for day
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 68
    target:
      device_id: 0e3b41f4d6adfcecbd7b25e030582a2a
  mode: single
- id: '1642526504100'
  alias: Turn on TV bias light
  description: ''
  trigger:
  - platform: device
    device_id: d57169b4050311eb87605dd332f99035
    domain: media_player
    entity_id: media_player.sony_bravia_tv
    type: playing
  condition:
  - condition: or
    conditions:
    - condition: time
      before: 06:00:00
      after: '18:00:00'
  action:
  - type: turn_on
    device_id: e6579d0ff24dc6983d622b7dc534659f
    entity_id: light.tv_light
    domain: light
  mode: single
- id: '1642526804653'
  alias: Turn off TV bias light
  description: ''
  trigger:
  - platform: device
    device_id: d57169b4050311eb87605dd332f99035
    domain: media_player
    entity_id: media_player.sony_bravia_tv
    type: turned_off
  condition: []
  action:
  - type: turn_off
    device_id: e6579d0ff24dc6983d622b7dc534659f
    entity_id: light.tv_light
    domain: light
  mode: single
- id: '1642689919936'
  alias: Turn on night alarm
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - device_id: 2707a9e748fb6372efc2520dd7a11576
    domain: alarm_control_panel
    entity_id: alarm_control_panel.alarmo
    type: arm_night
  mode: single
- id: '1642690101045'
  alias: Turn off night alarm
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - device_id: 2707a9e748fb6372efc2520dd7a11576
    domain: alarm_control_panel
    entity_id: alarm_control_panel.alarmo
    type: disarm
  mode: single
- id: '1642697138346'
  alias: Turn on away alarm
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    to: not_home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - device_id: 2707a9e748fb6372efc2520dd7a11576
    domain: alarm_control_panel
    entity_id: alarm_control_panel.alarmo
    type: arm_away
  mode: single
- id: '1642785019365'
  alias: Turn off away alarm
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    to: home
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - device_id: 2707a9e748fb6372efc2520dd7a11576
    domain: alarm_control_panel
    entity_id: alarm_control_panel.alarmo
    type: disarm
  mode: single
- id: '1646266387752'
  alias: View cameras - mobile
  description: ''
  trigger:
  - platform: state
    entity_id: input_button.view_cameras_phone
  condition: []
  action:
  - service: notify.mobile_app_abi_iphone_12
    data:
      message: Driveway
      data:
        attachment:
          content-type: jpeg
        push:
          category: camera
        entity_id: camera.driveway_cam
  - service: notify.mobile_app_abi_iphone_12
    data:
      data:
        attachment:
          content-type: jpeg
        push:
          category: camera
        entity_id: camera.backyard_cam
      message: Backyard
  mode: single
- id: '1646314071906'
  alias: Save lovelace config
  description: ''
  trigger:
  - platform: state
    entity_id: input_button.save_lovelace_config
  condition: []
  action:
  - service: shell_command.save_lovelace
    data: {}
  mode: single
- id: '1646318387526'
  alias: Generate readme
  description: ''
  trigger:
  - platform: state
    entity_id: input_button.generate_readme
  condition: []
  action:
  - service: readme.generate
    data: {}
  mode: single
- id: '1646585979943'
  alias: View cameras - tv
  description: ''
  trigger:
  - platform: state
    entity_id: input_button.view_cameras_tv
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.living_room_tv
    data:
      media_content_id: media-source://camera/camera.driveway_cam
      media_content_type: image/jpeg
    metadata:
      title: Driveway Cam
      thumbnail: /api/camera_proxy/camera.driveway_cam
      media_class: video
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://camera
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: media_player.play_media
    target:
      entity_id: media_player.living_room_tv
    data:
      media_content_id: media-source://camera/camera.backyard_cam
      media_content_type: image/jpeg
    metadata:
      title: Backyard Cam
      thumbnail: /api/camera_proxy/camera.backyard_cam
      media_class: video
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://camera
  mode: single
- id: '1646662551616'
  alias: Weather summary
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.office_speaker
      message: Today, it is going to be {{ states('weather.openweathermap_daily')
        }}. Currently, it is {{ state_attr('weather.openweathermap_hourly','temperature')
        | round }} 째F and it feels like {{ states('sensor.openweathermap_hourly_feels_like_temperature')
        | round }} 째F. Today's high will be {{ state_attr('weather.openweathermap_daily',
        'forecast')[0].temperature | round }} 째F and low will be {{ state_attr('weather.openweathermap_daily',
        'forecast')[0].templow | round }} 째F. Humidity will be {{ state_attr('weather.openweathermap_daily',
        'humidity') }}% with precipitation probability of {{ state_attr('weather.openweathermap_daily',
        'forecast')[0].precipitation_probability }}%
  mode: single
