- id: '1605886570099'
  alias: Living room lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '2:00'
    id: sunset
  - platform: time
    at: '23:00:00'
    id: time
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: sunset
      sequence:
      - type: turn_on
        device_id: 0885ed2690b46239fb5097c82e1f1073
        entity_id: light.living_room
        domain: light
    - conditions:
      - condition: trigger
        id: time
      sequence:
      - type: turn_off
        device_id: 0885ed2690b46239fb5097c82e1f1073
        entity_id: light.living_room
        domain: light
    default: []
  mode: single
- id: '1605887484325'
  alias: Bedroom light
  description: ''
  trigger:
  - platform: time
    at: input_datetime.bedroom_light_on
    id: 'on'
  - platform: time
    at: input_datetime.bedroom_light_off
    id: 'off'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: 'on'
      sequence:
      - type: turn_on
        device_id: 138506d6ceac3071a7ea57ba1d9b20c2
        entity_id: light.bedroom
        domain: light
    - conditions:
      - condition: trigger
        id: 'off'
      sequence:
      - type: turn_off
        device_id: 138506d6ceac3071a7ea57ba1d9b20c2
        entity_id: light.bedroom
        domain: light
    default: []
  mode: single
- id: '1607978571172'
  alias: High water usage alert
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.hourly_water_consumption
    above: '20'
  condition: []
  action:
  - service: notify.mobile_app_abi_iphone_15
    data:
      message: High water usage
  mode: single
- id: '1631369919205'
  alias: Check all doors
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  condition: []
  action:
  - service: notify.mobile_app_abi_iphone_15
    data:
      message: '{% set doors = expand(''group.doors'') | selectattr(''state'', ''in'',
        [''on'', ''open'']) | map(attribute=''name'') |  map(''replace'', '' Door'',
        '''')  | list %} {% set count = doors | count %} {% if count == 0 %} All doors
        are closed. {% else %} The {{ doors | join('', and '')}} door{{ ''s are ''
        if count > 1 else '' is '' }}open. {% endif %}'
      data:
        actions:
        - action: close_garage_door
          title: Close Garage Door
  mode: single
- id: '1631372133150'
  alias: Close garage door from iOS notification
  description: ''
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: close_garage_door
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.garage_door
    data: {}
  mode: single
- id: '1641389647705'
  alias: Thermostat
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
    id: day
  - platform: time
    at: '23:00:00'
    id: night
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: day
      sequence:
      - service: climate.set_temperature
        data:
          temperature: 68
          hvac_mode: heat
        target:
          entity_id: climate.living_room_thermostat
    - conditions:
      - condition: trigger
        id: night
      sequence:
      - service: climate.set_temperature
        data:
          temperature: 60
          hvac_mode: heat
        target:
          entity_id: climate.living_room_thermostat
    default: []
  mode: single
- id: '1642526504100'
  alias: TV bias light
  description: ''
  trigger:
  - platform: device
    device_id: d57169b4050311eb87605dd332f99035
    domain: media_player
    entity_id: media_player.living_room_sony_tv
    type: turned_on
    id: playing
  - platform: device
    type: turned_off
    device_id: d57169b4050311eb87605dd332f99035
    entity_id: remote.living_room_sony_tv
    domain: remote
    id: 'off'
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: playing
      - condition: time
        before: 06:00:00
        after: '20:00:00'
      sequence:
      - type: turn_on
        device_id: e6579d0ff24dc6983d622b7dc534659f
        entity_id: light.tv_light
        domain: light
    - conditions:
      - condition: trigger
        id: 'off'
      sequence:
      - type: turn_off
        device_id: e6579d0ff24dc6983d622b7dc534659f
        entity_id: light.tv_light
        domain: light
    default: []
  mode: single
- id: '1642785019365'
  alias: Alarm
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    to: not_home
    id: not_home
  - platform: state
    entity_id: group.family
    to: home
    id: home
  - platform: time
    at: '21:00:00'
    id: night
  - platform: time
    at: 06:00:00
    id: morning
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: not_home
      sequence:
      - device_id: 2707a9e748fb6372efc2520dd7a11576
        domain: alarm_control_panel
        entity_id: alarm_control_panel.alarmo
        type: arm_away
    - conditions:
      - condition: trigger
        id: home
      sequence:
      - device_id: 2707a9e748fb6372efc2520dd7a11576
        domain: alarm_control_panel
        entity_id: alarm_control_panel.alarmo
        type: disarm
    - conditions:
      - condition: trigger
        id:
        - night
      sequence:
      - device_id: 2707a9e748fb6372efc2520dd7a11576
        domain: alarm_control_panel
        entity_id: 49a957afb923faa365c0e3b01d9b8dac
        type: arm_night
    - conditions:
      - condition: trigger
        id:
        - morning
      sequence:
      - device_id: 2707a9e748fb6372efc2520dd7a11576
        domain: alarm_control_panel
        entity_id: 49a957afb923faa365c0e3b01d9b8dac
        type: disarm
    default: []
  mode: single
- id: '1646314071906'
  alias: Save lovelace config
  description: ''
  trigger:
  - platform: state
    entity_id: input_button.save_lovelace_config
  condition: []
  action:
  - service: shell_command.save_lovelace
    data: {}
  mode: single
- id: '1646318387526'
  alias: Generate readme
  description: ''
  trigger:
  - platform: state
    entity_id: input_button.generate_readme
  condition: []
  action:
  - service: readme.generate
    data: {}
  mode: single
- id: '1646662551616'
  alias: Weather summary
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition:
  - condition: time
    before: 00:00:00
    after: 00:00:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.office_speaker
      message: Today, it is going to be {{ states('weather.openweathermap_daily')
        }}. Currently, it is {{ state_attr('weather.openweathermap_hourly','temperature')
        | round }} 째F and it feels like {{ states('sensor.openweathermap_hourly_feels_like_temperature')
        | round }} 째F. Today's high will be {{ state_attr('weather.openweathermap_daily',
        'forecast')[0].temperature | round }} 째F and low will be {{ state_attr('weather.openweathermap_daily',
        'forecast')[0].templow | round }} 째F. Humidity will be {{ state_attr('weather.openweathermap_daily',
        'humidity') }}% with precipitation probability of {{ state_attr('weather.openweathermap_daily',
        'forecast')[0].precipitation_probability }}%
  mode: single
- id: '1650311187812'
  alias: Time to go home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.abi
    zone: zone.gsm
    event: enter
  condition:
  - condition: time
    before: '17:00:00'
    after: '12:00:00'
  action:
  - service: notify.mobile_app_ras_iphone_15
    data:
      title: "\U0001F55F \U0001F3E0"
      message: '{{ states("sensor.zenquote") }}'
  mode: single
- id: '1657803532514'
  alias: Front door camera refresh
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.front_door_camera_refresh
  condition: []
  action:
  - service: blink.trigger_camera
    data: {}
    target:
      device_id: 7d65e753c10ec0a0cfdc2de904a8990c
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
    enabled: true
  - service: blink.blink_update
    data: {}
  mode: single
- id: '1658145992175'
  alias: Living room switch
  description: ''
  trigger:
  - device_id: 1b5d209604c811ebbc13bb3e74b7e0b9
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: 8f72c511-1672-4388-b3ac-ece53bbbb1f2
    id: first button
  - device_id: 1b5d209604c811ebbc13bb3e74b7e0b9
    domain: hue
    platform: device
    type: initial_press
    subtype: 2
    unique_id: f00505fe-7392-4bef-b0a8-ecaf886679f0
    id: second button
  - device_id: 1b5d209604c811ebbc13bb3e74b7e0b9
    domain: hue
    platform: device
    type: initial_press
    subtype: 3
    unique_id: 48bb8675-e79b-40a2-a0fe-69c41a8a55d4
    id: third button
  - device_id: 1b5d209604c811ebbc13bb3e74b7e0b9
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    unique_id: 42c24591-b608-4c55-a61b-5f8a5603b054
    id: fourth button
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: first button
      sequence:
      - type: turn_on
        device_id: 1b61e4a804c811ebb1ffa7da09cbcb31
        entity_id: light.living_room_lamp_1
        domain: light
      - type: turn_on
        device_id: 1b62d42b04c811eba571f5d63aa9d83d
        entity_id: light.living_room_lamp_2
        domain: light
    - conditions:
      - condition: trigger
        id: second button
      sequence:
      - type: turn_on
        device_id: 1b63492404c811ebbcb5dd29bbe911b0
        entity_id: light.living_room_light_1
        domain: light
    - conditions:
      - condition: trigger
        id: third button
      sequence:
      - type: turn_on
        device_id: ae7c7d7804c811eb8fa71deb0d3d0c10
        entity_id: 15749989eeeb68032ff1e5e7f5118a44
        domain: switch
    - conditions:
      - condition: trigger
        id: fourth button
      sequence:
      - type: turn_off
        device_id: 0885ed2690b46239fb5097c82e1f1073
        entity_id: light.living_room
        domain: light
      - type: turn_off
        device_id: ae7c7d7804c811eb8fa71deb0d3d0c10
        entity_id: 62119a07512ae781ea54b6e9110efb24
        domain: light
    default: []
  mode: single
- id: '1678473761677'
  alias: Front door camera save image
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.front_door_access_control_window_door_is_open
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: blink.trigger_camera
    data: {}
    target:
      entity_id:
      - camera.blink_front_door
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
    enabled: false
  - service: blink.blink_update
    data: {}
  - service: camera.snapshot
    data:
      filename: /media/Images/Front Door/{{ now().strftime('%Y-%m-%d') }}/{{ now().strftime('%H-%M-%S')
        }}.jpg
    target:
      entity_id:
      - camera.blink_front_door
  mode: single
- id: '1678475033769'
  alias: Front door camera save video
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.front_door_access_control_window_door_is_open
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: blink.save_video
    data:
      name: Front Door
      filename: /media/videos/test.mp4
  mode: single
- id: '1686754760306'
  alias: Air purifier
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - type: turn_on
    device_id: f6bb2dcdba2fc2f2e0172dbc69d8bcfd
    entity_id: switch.air_purifier
    domain: switch
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: f6bb2dcdba2fc2f2e0172dbc69d8bcfd
    entity_id: switch.air_purifier
    domain: switch
  mode: single
