# https://www.home-assistant.io/getting-started/configuration/
homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config

# https://www.home-assistant.io/integrations/default_config/
default_config:

group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
automation: !include automations.yaml

tts: !include integrations/tts.yaml
http: !include integrations/http.yaml
rest: !include integrations/rest.yaml
mqtt: !include integrations/mqtt.yaml
sensor: !include integrations/sensor.yaml
readme: !include integrations/readme.yaml
logger: !include integrations/logger.yaml
frontend: !include integrations/frontend.yaml
recorder: !include integrations/recorder.yaml
template: !include integrations/template.yaml
prometheus: !include integrations/prometheus.yaml
multiscrape: !include integrations/multiscrape.yaml
shell_command: !include integrations/shell_command.yaml
utility_meter: !include integrations/utility_meter.yaml
