# https://www.home-assistant.io/getting-started/configuration/
homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config

# https://www.home-assistant.io/integrations/default_config/
default_config:

group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml

http: !include integrations/http.yaml
readme: !include integrations/readme.yaml
logger: !include integrations/logger.yaml
frontend: !include integrations/frontend.yaml
recorder: !include integrations/recorder.yaml
# influxdb: !include integrations/influxdb.yaml
prometheus: !include integrations/prometheus.yaml
panel_iframe: !include integrations/panel_iframe.yaml
shell_command: !include integrations/shell_command.yaml
utility_meter: !include integrations/utility_meter.yaml
generic_hygrostat: !include integrations/generic_hygrostat.yaml

tts: !include_dir_merge_list integrations/tts
light: !include_dir_merge_list integrations/light
camera: !include_dir_merge_list integrations/camera
notify: !include_dir_merge_list integrations/notify
sensor: !include_dir_merge_list integrations/sensor
