custom_header:
  active_tab_color: var(--state-icon-active-color)
  background: var(--app-header-background-color)
  button_text:
    options: "{{ hours12 }}:{{ minutesLZ }} {{ AMPM }} <br>  <ha-icon icon='mdi:weather-{%\
      \ if is_state(\"weather.weather\", \"partlycloudy\") -%}partly-cloudy{%- else\
      \ -%}{{ states('weather.weather') }}{%- endif %}'></ha-icon> {{ state_attr('weather.weather',\
      \ 'temperature') }} °F"
  chevrons: false
  compact_mode: true
  editor_warnings: false
  elements_color: var(--app-header-text-color)
  hidden_tab_redirect: false
  tab_indicator_color: var(--state-icon-active-color)
resources:
  - type: js
    url: /hacsfiles/bar-card/bar-card.js
  - type: js
    url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
  - type: js
    url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
  - type: js
    url: /hacsfiles/lovelace-card-templater/lovelace-card-templater.js
  - type: module
    url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
  - type: module
    url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
  - type: module
    url: /hacsfiles/lovelace-battery-entity/battery-entity.js
  - type: module
    url: /hacsfiles/lovelace-auto-entities/auto-entities.js
  - type: module
    url: /hacsfiles/lovelace-state-switch/state-switch.js
  - type: module
    url: /hacsfiles/lovelace-card-tools/card-tools.js
  - type: module
    url: /hacsfiles/lovelace-card-mod/card-mod.js
  - type: module
    url: /hacsfiles/custom-header/custom-header.js
  - type: module
    url: /hacsfiles/button-card/button-card.js
  - type: module
    url: /hacsfiles/search-card/search-card.js
  - type: module
    url: /local/home-card/home-card.js
title: Ada
views:
  - badges: []
    cards:
      - entity: weather.dark_sky
        name: ' '
        secondary_info:
          - humidity
        type: custom:simple-weather-card
      - background: transparent
        entities:
          - entity: light.living_room
            type: downstairs_light
          - entity: binary_sensor.front_door
            state_map:
              off: closed
              on: open
            type: garage
          - entity: binary_sensor.front_door
            state_map:
              off: on
              on: off
            type: door
          - entity: person.abi
            state_map:
              off: not_home
              on: home
            type: car
        resources:
          - entity: camera.driveway_camera
            icon: mdi:cctv
          - entity: binary_sensor.driveway_motion
            icon: mdi:motion-sensor
          - entity: camera.backyard_camera
            icon: mdi:cctv
          - entity: binary_sensor.backyard_motion
            icon: mdi:motion-sensor
        theme: two_story_with_garage
        type: custom:home-card
      - cards:
          - aspect_ratio: 80%
            elements:
              - entity: light.dining_room
                icon: mdi:floor-lamp
                style:
                  left: 12%
                  top: 44%
                type: state-icon
              - entity: light.living_room_light_1
                icon: mdi:lamp
                style:
                  left: 20%
                  top: 70%
                type: state-icon
              - entity: light.living_room_light_2
                icon: mdi:lamp
                style:
                  left: 45%
                  top: 60%
                type: state-icon
              - entity: media_player.living_room_tv
                icon: mdi:television
                style:
                  left: 33%
                  top: 52%
                type: state-icon
              - entity: media_player.living_room_speaker
                icon: mdi:google-home
                style:
                  left: 15%
                  top: 60%
                type: state-icon
              - entity: light.office_light
                icon: mdi:desk-lamp
                style:
                  left: 70%
                  top: 50%
                tap_action:
                  action: toggle
                type: state-icon
              - entity: light.master_bedroom_light
                icon: mdi:lamp
                style:
                  left: 75%
                  top: 15%
                tap_action:
                  action: toggle
                type: state-icon
              - entity: media_player.master_bedroom_speaker
                icon: mdi:google-home
                style:
                  left: 65%
                  top: 20%
                type: state-icon
              - entity: switch.coffee
                icon: mdi:coffee-maker
                style:
                  left: 30%
                  top: 35%
                type: state-icon
              - entity: switch.rice_cooker
                icon: mdi:pot
                style:
                  left: 35%
                  top: 25%
                type: state-icon
              - entity: media_player.kitchen_speaker
                icon: mdi:amazon-alexa
                style:
                  left: 40%
                  top: 35%
                type: state-icon
            image: /local/floorplan/floorplan.png
            type: picture-elements
          - entity: alarm_control_panel.alexa_guard
            name: ' '
            states:
              - arm_home
              - arm_away
            type: alarm-panel
        type: custom:vertical-stack-in-card
    icon: mdi:home
    panel: false
    path: home
    title: home
  - badges: []
    cards:
      - cards:
          - cards:
              - entity: light.living_room
                icon: mdi:sofa
                type: custom:button-card
              - entity: light.office
                icon: mdi:desk-lamp
                type: custom:button-card
              - entity: light.master_bedroom
                icon: mdi:bed-king
                type: custom:button-card
            type: horizontal-stack
          - cards:
              - entity: light.dining_room
                icon: mdi:silverware-fork-knife
                type: custom:button-card
              - entity: switch.coffee
                icon: mdi:coffee-maker
                type: custom:button-card
              - entity: switch.rice_cooker
                icon: mdi:rice
                type: custom:button-card
            type: horizontal-stack
        type: custom:vertical-stack-in-card
      - entities:
          - entity: sensor.living_room_sensor_temperature
          - entity: sensor.living_room_sensor_humidity
            show_line: false
            y_axis: secondary
        name: Living Room
        show:
          average: true
          extrema: true
          fill: fade
          icon_adaptive_color: true
          labels: false
          labels_secondary: false
          legend: false
          points: false
        type: custom:mini-graph-card
      - entities:
          - entity: sensor.basement_sensor_temperature
          - entity: sensor.basement_sensor_humidity
            show_line: false
            y_axis: secondary
        name: Basement
        show:
          average: true
          extrema: true
          fill: fade
          icon_adaptive_color: true
          labels: false
          labels_secondary: false
          legend: false
          points: false
        type: custom:mini-graph-card
      - entities:
          - entity: sensor.dark_sky_temperature
          - entity: sensor.dark_sky_humidity
            show_line: false
            y_axis: secondary
        name: Outside
        show:
          average: true
          extrema: true
          fill: fade
          icon_adaptive_color: true
          labels: false
          labels_secondary: false
          legend: false
          points: false
        type: custom:mini-graph-card
    icon: mdi:floor-plan
    panel: false
    path: rooms
    title: rooms
  - badges: []
    cards:
      - camera_image: camera.driveway_camera
        entities:
          - entity: binary_sensor.driveway_motion
          - entity: binary_sensor.front_door
          - entity: binary_sensor.back_door
        type: picture-glance
      - camera_image: camera.backyard_camera
        entities:
          - entity: sensor.backyard_camera_battery_level
          - entity: switch.backyard_camera_torch
          - entity: switch.backyard_camera_night_vision
          - entity: binary_sensor.backyard_motion
          - entity: binary_sensor.slider
        type: picture-glance
    icon: mdi:cctv
    path: camera
    title: camera
  - badges: []
    cards:
      - cards:
          - artwork: cover
            entity: media_player.sony_bravia_tv
            icon: mdi:television
            info: short
            shortcuts:
              buttons:
                - icon: mdi:apple
                  id: HDMI 3
                  name: Apple TV
                  type: source
                - icon: mdi:playstation
                  id: HDMI 4
                  name: PS4
                  type: source
            source: icon
            type: custom:mini-media-player
          - artwork: cover
            entity: media_player.living_room_apple_tv
            icon: mdi:cast
            info: short
            source: icon
            type: custom:mini-media-player
          - artwork: cover
            entity: media_player.living_room_tv
            icon: mdi:cast
            info: short
            source: icon
            type: custom:mini-media-player
        type: custom:vertical-stack-in-card
      - artwork: cover
        entity: media_player.kitchen_speaker
        icon: mdi:amazon-alexa
        info: short
        source: icon
        type: custom:mini-media-player
      - cards:
          - artwork: cover
            entity: media_player.living_room_speaker
            icon: mdi:google-home
            info: short
            source: icon
            type: custom:mini-media-player
          - artwork: cover
            entity: media_player.office_speaker
            icon: mdi:google-home
            info: short
            source: icon
            type: custom:mini-media-player
          - artwork: cover
            entity: media_player.master_bedroom_speaker
            icon: mdi:google-home
            info: short
            source: icon
            type: custom:mini-media-player
          - artwork: cover
            entity: media_player.speakers
            icon: mdi:cast-audio
            info: short
            source: icon
            type: custom:mini-media-player
        type: custom:vertical-stack-in-card
    icon: mdi:music
    panel: false
    path: media
    title: media
  - badges: []
    cards:
      - cards:
          - entities:
              - entity: sensor.last_boot
              - align: split
                animation: off
                entities:
                  - entity: sensor.processor_use
                  - entity: sensor.memory_use_percent
                  - entity: sensor.disk_use_percent
                height: 30px
                severity:
                  - color: green
                    value: 50
                  - color: orange
                    value: 75
                  - color: red
                    value: 100
                title_position: inside
                type: custom:bar-card
            show_header_toggle: false
            title: System
            type: entities
          - entities:
              - entity: sensor.cpu_temperature
                show_state: true
              - entity: sensor.gpu_temperature
                show_state: true
            name: ' '
            show:
              fill: fade
              icon: false
              labels: false
              labels_secondary: true
              legend: false
              points: false
            type: custom:mini-graph-card
        type: custom:vertical-stack-in-card
      - cards:
          - entities:
              - entity: sensor.google_wifi_uptime
              - entity: sensor.google_wifi_status
              - entity: sensor.google_wifi_local_ip
              - entity: sensor.local_ip
            show_header_toggle: false
            title: Network
            type: entities
          - entities:
              - entity: sensor.network_in_eth0
                show_state: true
              - entity: sensor.network_out_eth0
                show_state: true
            name: ' '
            show:
              fill: fade
              icon: false
              labels: false
              labels_secondary: false
              legend: false
              points: false
            type: custom:mini-graph-card
        type: custom:vertical-stack-in-card
      - cards:
          - entities:
              - sensor.system_uptime
              - entity: sensor.current_version
                icon: mdi:folder-download
              - sensor.latest_version
              - binary_sensor.updater
              - entity: sensor.hacs
                name: Store
                tap_action:
                  action: navigate
                  navigation_path: /hacs
              - entity: sensor.home_assistant_v2_db
            show_header_toggle: false
            title: Home Assistant
            type: entities
          - content: "| Domain | Count |\n| :--- | ---: |\n| **Automations** | {{\
              \ states.automation | count }} |\n| **Sensors** | {{ states.sensor |\
              \ count }} |\n| **Binary Sensors** | {{ states.binary_sensor | count\
              \ }} |\n| **Lights** | {{ states.light | count }} |\n| **Switches**\
              \ | {{ states.switch | count }} |\n| **Media Players** | {{ states.media_player\
              \ | count }} |\n| **Device Trackers** | {{ states.device_tracker | count\
              \ }}\n| **Persons** | {{ states.person | count }} |\n| **Zones** | {{\
              \ states.zone | count }} |"
            type: markdown
        type: custom:vertical-stack-in-card
      - cards:
          - entities:
              - entity: sensor.last_boot
              - align: split
                animation: off
                entities:
                  - entity: sensor.camera_cpu_use_percent
                    name: CPU Usage
                  - entity: sensor.camera_memory_use_percent
                    name: Memory Usage
                height: 30px
                severity:
                  - color: green
                    value: 50
                  - color: orange
                    value: 75
                  - color: red
                    value: 100
                title_position: inside
                type: custom:bar-card
            show_header_toggle: false
            title: Camera
            type: entities
        type: vertical-stack
      - card:
          show_header_toggle: false
          title: Utilities
          type: entities
        filter:
          include:
            - entity_id: sensor.*usage*
        type: custom:auto-entities
      - card:
          show_header_toggle: false
          title: Batteries
          type: entities
        filter:
          include:
            - entity_id: sensor.*battery*
        type: custom:auto-entities
    icon: mdi:home-analytics
    panel: false
    path: analytics
    title: Analytics
  - badges: []
    cards:
      - max_results: 10
        type: custom:search-card
    icon: mdi:magnify
    path: search
    title: search
  - badges: []
    cards:
      - content: "**Lights:**: {{ states.light | selectattr('state', 'eq',  'on')\
          \ | list | count }} on and {{ states.light | selectattr('state', 'eq', \
          \ 'off') | list | count }} off.\n**Switches:**: {{ states.switch | selectattr('state',\
          \ 'eq',  'on') | list | count }} on and {{ states.switch | selectattr('state',\
          \ 'eq',  'off') | list | count }} off."
        title: Overview
        type: markdown
    icon: mdi:bug
    panel: false
    path: test
    title: test
