# https://www.home-assistant.io/integrations/sensor.mqtt/
- platform: mqtt
  name: Water Consumption
  icon: mdi:water
  unit_of_measurement: gal
  state_topic: homeassistant/sensor/1461742372/reading
  state_class: total_increasing
  value_template: "{{ value_json.Message.Consumption }}"
  json_attributes_topic: homeassistant/sensor/1461742372/reading
  json_attributes_template: "{{ value_json | tojson }}"

- platform: mqtt
  name: Electricity Consumption
  icon: mdi:flash
  device_class: energy
  unit_of_measurement: kWh
  state_topic: homeassistant/sensor/69109638/reading
  state_class: total_increasing
  value_template: "{{ value_json.Message.Consumption | multiply(0.01) | round() }}"
  json_attributes_topic: homeassistant/sensor/69109638/reading
  json_attributes_template: "{{ value_json | tojson }}"
