# https://www.home-assistant.io/integrations/rest
- platform: rest
  name: Data Usage
  resource: !secret data_usage_url
  scan_interval: 3600
  value_template: '{{ value_json.total_usage }}'
  unit_of_measurement: GB
  json_attributes:
    - allowable_usage
    - remaining_usage
