# https://www.home-assistant.io/integrations/systemmonitor
- platform: systemmonitor
  resources:
    # - type: disk_use_percent
    #   arg: /
    # - type: disk_use
    #   arg: /
    # - type: memory_use_percent
    # - type: memory_use
    # - type: network_in
    #   arg: eth0
    # - type: network_out
    #   arg: eth0
    # - type: processor_use
    - type: last_boot
