# https://www.home-assistant.io/integrations/template/
- platform: template
  sensors:
    living_room_temperature:
      friendly_name: 'Living Room Temperature'
      unique_id: 'living_room_temperature'
      device_class: 'temperature'
      unit_of_measurement: '°F'
      value_template: '{{ state_attr("climate.living_room_thermostat", "current_temperature") | int }}'

    air_quality:
        friendly_name: Air Quality
        value_template: >-
          {%if states.sensor.waqi.state | float <= 50 %}Good
          {% elif states.sensor.waqi.state | float > 50 | float <= 100 %}Moderate
          {% elif states.sensor.waqi.state | float > 100 | float <= 150 %}Unhealthy for Sensitive Groups
          {% elif states.sensor.waqi.state | float > 150 | float <= 200 %}Unhealthy
          {% elif states.sensor.waqi.state | float > 200 | float <= 250 %}Very unhealthy
          {% elif states.sensor.waqi.state | float > 250 | float <= 300 %}Hazardous
          {%- endif %}
        icon_template: >-
          {%if states.sensor.waqi.state | float <= 50 %}mdi:emoticon-excited
          {% elif states.sensor.waqi.state | float > 50 | float <= 100 %}mdi:emoticon-happy
          {% elif states.sensor.waqi.state | float > 100 | float <= 150 %}mdi:emoticon-neutral
          {% elif states.sensor.waqi.state | float > 150 | float <= 200 %}mdi:emoticon-sad
          {% elif states.sensor.waqi.state | float > 200 | float <= 250 %}mdi:emoticon-dead
          {% elif states.sensor.waqi.state | float > 250 | float <= 300 %}mdi:biohazard
          {%- endif %}
