# https://www.home-assistant.io/integrations/mjpeg
- platform: mjpeg
  name: Driveway Cam
  mjpeg_url: !secret driveway_camera_video_url
  username: !secret camera_username
  password: !secret camera_password
  authentication: basic

- platform: mjpeg
  name: Backyard Cam
  mjpeg_url: !secret backyard_camera_video_url
  username: !secret camera_username
  password: !secret camera_password
  authentication: basic
 
- platform: mjpeg
  name: Kitchen Cam
  mjpeg_url: !secret kitchen_camera_video_url
  username: !secret camera_username
  password: !secret camera_password
  authentication: basic
